# Numpy Introduction

In [58]:
# pip install numpy

In [59]:
import numpy as np

# What is an array?

An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis, and machine learning. 

In Python, the NumPy library provides support for arrays and enables efficient numerical operations on them. NumPy arrays are more efficient than Python lists for numerical operations because they are implemented in C and allow for vectorized operations.

In [60]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [61]:
a2 = a[np.newaxis,  :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [62]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# **Assignments:** Why do we have 1D, 2D or 3D arrays and where we need them in Data Science?

---

# Creating Arrays with Numpy

In [63]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])

In [64]:
type(a) # type of array

numpy.ndarray

In [65]:
a.dtype # data type of array elements

dtype('int32')

In [66]:
type(b)

numpy.ndarray

In [67]:
b.dtype

dtype('int32')

In [68]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [69]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# initialize arrays

In [70]:
zeros = np.zeros((2, 5)) # (rows, columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
zeros.dtype

dtype('float64')

In [72]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
ones.dtype

dtype('float64')

In [74]:
full = np.full((2, 5), 7.5)
full

array([[7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5]])

In [75]:
full.dtype

dtype('float64')

In [76]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
identity.dtype

dtype('float64')

# array attributes

In [78]:
a.shape # shape of array

(7,)

In [79]:
len(b) # give us the length of array

2

In [80]:
b.size # gives us the numbers of elements in array

14

In [81]:
b.ndim # give us the dimension of array

2

# basic operations

In [82]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [86]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [87]:
# addition
h = a + b
h 

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [89]:
# another method
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [90]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [91]:
# division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [92]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])