# Numpy (Part-2)

In [1]:
import numpy as np

In [17]:
empty = np.empty((2, 4))
print(empty)
print("------------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------
[0. 0. 0. 0.]


In [23]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [26]:
# array of even numbers from 0 to 23
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [27]:
# array of odd numbers from 0 to 23
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [32]:
# specific differnce between numbers
diff = np.arange(0, 23, 0.515) # 0.515 is the difference between numbers
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [56]:
lin = np.linspace(0, 10, num=15)
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [53]:
lin.dtype

dtype('float64')

In [65]:
# define the dtype of array
x = np.arange(0 ,22.6, 1.5, dtype=np.int8)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

# **Assignment:** What is the difference between int32, 64 ya float 32, 64, 16..... In ka matlab kia hy? Why do we use one and not the other one?

In [66]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [68]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [71]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Arrays

In [72]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array

In [85]:
len(x)

2

In [87]:
len(y)

1

In [82]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
w = np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [93]:
z1 = np.concatenate((w,x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [99]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [100]:
len(array_example)

3

In [101]:
array_example.size

24

In [102]:
array_example.dtype

dtype('int32')

In [103]:
array_example.shape

(3, 2, 4)

In [109]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [110]:
# reshape the a 
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [111]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [118]:
a2.reshape(3,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [123]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [129]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [128]:
c = a[: , np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# indexing and slicing

In [130]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [137]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [151]:
# filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [154]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [156]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])